apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tier: database

resources:
  - serviceaccount.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
