apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: three-tier

commonLabels:
  app: three-tier-app

resources:
   
  - Backend/deployment.yaml
  - Backend/service.yaml

  # Database
  - Database/pvc.yaml
  - Database/deployment.yaml
  - Database/service.yaml
  - Database/secret.yaml

  # Frontend
  - Frontend/deployment.yaml
  - Frontend/service.yaml
  - ingress.yaml